version: '3'
services:
    database:
        build: ./mysql
        container_name: sistema-de-vendas
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/.dbdata:/var/lib/mysql
        networks:
            - project

networks:
    project:
        driver: bridge




